// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExtraProto.proto

package com.trans.pixel.protoc;

public final class ExtraProto {
  private ExtraProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StarOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // optional int32 maxlevel = 2;
    /**
     * <code>optional int32 maxlevel = 2;</code>
     */
    boolean hasMaxlevel();
    /**
     * <code>optional int32 maxlevel = 2;</code>
     */
    int getMaxlevel();

    // optional int32 maxskill = 3;
    /**
     * <code>optional int32 maxskill = 3;</code>
     */
    boolean hasMaxskill();
    /**
     * <code>optional int32 maxskill = 3;</code>
     */
    int getMaxskill();

    // optional int32 star = 4;
    /**
     * <code>optional int32 star = 4;</code>
     */
    boolean hasStar();
    /**
     * <code>optional int32 star = 4;</code>
     */
    int getStar();

    // optional int32 level = 5;
    /**
     * <code>optional int32 level = 5;</code>
     */
    boolean hasLevel();
    /**
     * <code>optional int32 level = 5;</code>
     */
    int getLevel();

    // optional int32 count = 6;
    /**
     * <code>optional int32 count = 6;</code>
     */
    boolean hasCount();
    /**
     * <code>optional int32 count = 6;</code>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code com.trans.pixel.protoc.Star}
   *
   * <pre>
   *&#47;/////// ExtraProto
   * </pre>
   */
  public static final class Star extends
      com.google.protobuf.GeneratedMessage
      implements StarOrBuilder {
    // Use Star.newBuilder() to construct.
    private Star(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Star(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Star defaultInstance;
    public static Star getDefaultInstance() {
      return defaultInstance;
    }

    public Star getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Star(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxlevel_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              maxskill_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              star_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              level_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Star_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Star_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trans.pixel.protoc.ExtraProto.Star.class, com.trans.pixel.protoc.ExtraProto.Star.Builder.class);
    }

    public static com.google.protobuf.Parser<Star> PARSER =
        new com.google.protobuf.AbstractParser<Star>() {
      public Star parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Star(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Star> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional int32 maxlevel = 2;
    public static final int MAXLEVEL_FIELD_NUMBER = 2;
    private int maxlevel_;
    /**
     * <code>optional int32 maxlevel = 2;</code>
     */
    public boolean hasMaxlevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 maxlevel = 2;</code>
     */
    public int getMaxlevel() {
      return maxlevel_;
    }

    // optional int32 maxskill = 3;
    public static final int MAXSKILL_FIELD_NUMBER = 3;
    private int maxskill_;
    /**
     * <code>optional int32 maxskill = 3;</code>
     */
    public boolean hasMaxskill() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 maxskill = 3;</code>
     */
    public int getMaxskill() {
      return maxskill_;
    }

    // optional int32 star = 4;
    public static final int STAR_FIELD_NUMBER = 4;
    private int star_;
    /**
     * <code>optional int32 star = 4;</code>
     */
    public boolean hasStar() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 star = 4;</code>
     */
    public int getStar() {
      return star_;
    }

    // optional int32 level = 5;
    public static final int LEVEL_FIELD_NUMBER = 5;
    private int level_;
    /**
     * <code>optional int32 level = 5;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 level = 5;</code>
     */
    public int getLevel() {
      return level_;
    }

    // optional int32 count = 6;
    public static final int COUNT_FIELD_NUMBER = 6;
    private int count_;
    /**
     * <code>optional int32 count = 6;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 count = 6;</code>
     */
    public int getCount() {
      return count_;
    }

    private void initFields() {
      id_ = 0;
      maxlevel_ = 0;
      maxskill_ = 0;
      star_ = 0;
      level_ = 0;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, maxlevel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, maxskill_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, star_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, count_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxlevel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxskill_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, star_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.trans.pixel.protoc.ExtraProto.Star parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.Star parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.trans.pixel.protoc.ExtraProto.Star prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.trans.pixel.protoc.Star}
     *
     * <pre>
     *&#47;/////// ExtraProto
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.trans.pixel.protoc.ExtraProto.StarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Star_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Star_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trans.pixel.protoc.ExtraProto.Star.class, com.trans.pixel.protoc.ExtraProto.Star.Builder.class);
      }

      // Construct using com.trans.pixel.protoc.ExtraProto.Star.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxlevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        maxskill_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        star_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Star_descriptor;
      }

      public com.trans.pixel.protoc.ExtraProto.Star getDefaultInstanceForType() {
        return com.trans.pixel.protoc.ExtraProto.Star.getDefaultInstance();
      }

      public com.trans.pixel.protoc.ExtraProto.Star build() {
        com.trans.pixel.protoc.ExtraProto.Star result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.trans.pixel.protoc.ExtraProto.Star buildPartial() {
        com.trans.pixel.protoc.ExtraProto.Star result = new com.trans.pixel.protoc.ExtraProto.Star(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxlevel_ = maxlevel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxskill_ = maxskill_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.star_ = star_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trans.pixel.protoc.ExtraProto.Star) {
          return mergeFrom((com.trans.pixel.protoc.ExtraProto.Star)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trans.pixel.protoc.ExtraProto.Star other) {
        if (other == com.trans.pixel.protoc.ExtraProto.Star.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMaxlevel()) {
          setMaxlevel(other.getMaxlevel());
        }
        if (other.hasMaxskill()) {
          setMaxskill(other.getMaxskill());
        }
        if (other.hasStar()) {
          setStar(other.getStar());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.trans.pixel.protoc.ExtraProto.Star parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.trans.pixel.protoc.ExtraProto.Star) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional int32 maxlevel = 2;
      private int maxlevel_ ;
      /**
       * <code>optional int32 maxlevel = 2;</code>
       */
      public boolean hasMaxlevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 maxlevel = 2;</code>
       */
      public int getMaxlevel() {
        return maxlevel_;
      }
      /**
       * <code>optional int32 maxlevel = 2;</code>
       */
      public Builder setMaxlevel(int value) {
        bitField0_ |= 0x00000002;
        maxlevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 maxlevel = 2;</code>
       */
      public Builder clearMaxlevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxlevel_ = 0;
        onChanged();
        return this;
      }

      // optional int32 maxskill = 3;
      private int maxskill_ ;
      /**
       * <code>optional int32 maxskill = 3;</code>
       */
      public boolean hasMaxskill() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 maxskill = 3;</code>
       */
      public int getMaxskill() {
        return maxskill_;
      }
      /**
       * <code>optional int32 maxskill = 3;</code>
       */
      public Builder setMaxskill(int value) {
        bitField0_ |= 0x00000004;
        maxskill_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 maxskill = 3;</code>
       */
      public Builder clearMaxskill() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxskill_ = 0;
        onChanged();
        return this;
      }

      // optional int32 star = 4;
      private int star_ ;
      /**
       * <code>optional int32 star = 4;</code>
       */
      public boolean hasStar() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 star = 4;</code>
       */
      public int getStar() {
        return star_;
      }
      /**
       * <code>optional int32 star = 4;</code>
       */
      public Builder setStar(int value) {
        bitField0_ |= 0x00000008;
        star_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 star = 4;</code>
       */
      public Builder clearStar() {
        bitField0_ = (bitField0_ & ~0x00000008);
        star_ = 0;
        onChanged();
        return this;
      }

      // optional int32 level = 5;
      private int level_ ;
      /**
       * <code>optional int32 level = 5;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 level = 5;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>optional int32 level = 5;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000010;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 level = 5;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        onChanged();
        return this;
      }

      // optional int32 count = 6;
      private int count_ ;
      /**
       * <code>optional int32 count = 6;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 count = 6;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>optional int32 count = 6;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000020;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 count = 6;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        count_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.trans.pixel.protoc.Star)
    }

    static {
      defaultInstance = new Star(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.trans.pixel.protoc.Star)
  }

  public interface StarListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.trans.pixel.protoc.Star data = 1;
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    java.util.List<com.trans.pixel.protoc.ExtraProto.Star> 
        getDataList();
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    com.trans.pixel.protoc.ExtraProto.Star getData(int index);
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    java.util.List<? extends com.trans.pixel.protoc.ExtraProto.StarOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    com.trans.pixel.protoc.ExtraProto.StarOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.trans.pixel.protoc.StarList}
   */
  public static final class StarList extends
      com.google.protobuf.GeneratedMessage
      implements StarListOrBuilder {
    // Use StarList.newBuilder() to construct.
    private StarList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StarList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StarList defaultInstance;
    public static StarList getDefaultInstance() {
      return defaultInstance;
    }

    public StarList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StarList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<com.trans.pixel.protoc.ExtraProto.Star>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readMessage(com.trans.pixel.protoc.ExtraProto.Star.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_StarList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_StarList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trans.pixel.protoc.ExtraProto.StarList.class, com.trans.pixel.protoc.ExtraProto.StarList.Builder.class);
    }

    public static com.google.protobuf.Parser<StarList> PARSER =
        new com.google.protobuf.AbstractParser<StarList>() {
      public StarList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StarList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StarList> getParserForType() {
      return PARSER;
    }

    // repeated .com.trans.pixel.protoc.Star data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.trans.pixel.protoc.ExtraProto.Star> data_;
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    public java.util.List<com.trans.pixel.protoc.ExtraProto.Star> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    public java.util.List<? extends com.trans.pixel.protoc.ExtraProto.StarOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    public com.trans.pixel.protoc.ExtraProto.Star getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
     */
    public com.trans.pixel.protoc.ExtraProto.StarOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.trans.pixel.protoc.ExtraProto.StarList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.StarList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.trans.pixel.protoc.ExtraProto.StarList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.trans.pixel.protoc.StarList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.trans.pixel.protoc.ExtraProto.StarListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_StarList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_StarList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trans.pixel.protoc.ExtraProto.StarList.class, com.trans.pixel.protoc.ExtraProto.StarList.Builder.class);
      }

      // Construct using com.trans.pixel.protoc.ExtraProto.StarList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_StarList_descriptor;
      }

      public com.trans.pixel.protoc.ExtraProto.StarList getDefaultInstanceForType() {
        return com.trans.pixel.protoc.ExtraProto.StarList.getDefaultInstance();
      }

      public com.trans.pixel.protoc.ExtraProto.StarList build() {
        com.trans.pixel.protoc.ExtraProto.StarList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.trans.pixel.protoc.ExtraProto.StarList buildPartial() {
        com.trans.pixel.protoc.ExtraProto.StarList result = new com.trans.pixel.protoc.ExtraProto.StarList(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trans.pixel.protoc.ExtraProto.StarList) {
          return mergeFrom((com.trans.pixel.protoc.ExtraProto.StarList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trans.pixel.protoc.ExtraProto.StarList other) {
        if (other == com.trans.pixel.protoc.ExtraProto.StarList.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.trans.pixel.protoc.ExtraProto.StarList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.trans.pixel.protoc.ExtraProto.StarList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.trans.pixel.protoc.Star data = 1;
      private java.util.List<com.trans.pixel.protoc.ExtraProto.Star> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<com.trans.pixel.protoc.ExtraProto.Star>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.trans.pixel.protoc.ExtraProto.Star, com.trans.pixel.protoc.ExtraProto.Star.Builder, com.trans.pixel.protoc.ExtraProto.StarOrBuilder> dataBuilder_;

      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public java.util.List<com.trans.pixel.protoc.ExtraProto.Star> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.Star getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder setData(
          int index, com.trans.pixel.protoc.ExtraProto.Star value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder setData(
          int index, com.trans.pixel.protoc.ExtraProto.Star.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder addData(com.trans.pixel.protoc.ExtraProto.Star value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder addData(
          int index, com.trans.pixel.protoc.ExtraProto.Star value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder addData(
          com.trans.pixel.protoc.ExtraProto.Star.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder addData(
          int index, com.trans.pixel.protoc.ExtraProto.Star.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.trans.pixel.protoc.ExtraProto.Star> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.Star.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.StarOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public java.util.List<? extends com.trans.pixel.protoc.ExtraProto.StarOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.Star.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.trans.pixel.protoc.ExtraProto.Star.getDefaultInstance());
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.Star.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.trans.pixel.protoc.ExtraProto.Star.getDefaultInstance());
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Star data = 1;</code>
       */
      public java.util.List<com.trans.pixel.protoc.ExtraProto.Star.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.trans.pixel.protoc.ExtraProto.Star, com.trans.pixel.protoc.ExtraProto.Star.Builder, com.trans.pixel.protoc.ExtraProto.StarOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.trans.pixel.protoc.ExtraProto.Star, com.trans.pixel.protoc.ExtraProto.Star.Builder, com.trans.pixel.protoc.ExtraProto.StarOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.trans.pixel.protoc.StarList)
    }

    static {
      defaultInstance = new StarList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.trans.pixel.protoc.StarList)
  }

  public interface FenjieOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;
    /**
     * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
     */
    boolean hasLootlist();
    /**
     * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
     */
    com.trans.pixel.protoc.Base.RewardInfo getLootlist();
    /**
     * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
     */
    com.trans.pixel.protoc.Base.RewardInfoOrBuilder getLootlistOrBuilder();
  }
  /**
   * Protobuf type {@code com.trans.pixel.protoc.Fenjie}
   */
  public static final class Fenjie extends
      com.google.protobuf.GeneratedMessage
      implements FenjieOrBuilder {
    // Use Fenjie.newBuilder() to construct.
    private Fenjie(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Fenjie(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Fenjie defaultInstance;
    public static Fenjie getDefaultInstance() {
      return defaultInstance;
    }

    public Fenjie getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Fenjie(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.trans.pixel.protoc.Base.RewardInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = lootlist_.toBuilder();
              }
              lootlist_ = input.readMessage(com.trans.pixel.protoc.Base.RewardInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lootlist_);
                lootlist_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Fenjie_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Fenjie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trans.pixel.protoc.ExtraProto.Fenjie.class, com.trans.pixel.protoc.ExtraProto.Fenjie.Builder.class);
    }

    public static com.google.protobuf.Parser<Fenjie> PARSER =
        new com.google.protobuf.AbstractParser<Fenjie>() {
      public Fenjie parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Fenjie(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Fenjie> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;
    public static final int LOOTLIST_FIELD_NUMBER = 2;
    private com.trans.pixel.protoc.Base.RewardInfo lootlist_;
    /**
     * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
     */
    public boolean hasLootlist() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
     */
    public com.trans.pixel.protoc.Base.RewardInfo getLootlist() {
      return lootlist_;
    }
    /**
     * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
     */
    public com.trans.pixel.protoc.Base.RewardInfoOrBuilder getLootlistOrBuilder() {
      return lootlist_;
    }

    private void initFields() {
      id_ = 0;
      lootlist_ = com.trans.pixel.protoc.Base.RewardInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, lootlist_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, lootlist_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.Fenjie parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.trans.pixel.protoc.ExtraProto.Fenjie prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.trans.pixel.protoc.Fenjie}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Fenjie_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Fenjie_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trans.pixel.protoc.ExtraProto.Fenjie.class, com.trans.pixel.protoc.ExtraProto.Fenjie.Builder.class);
      }

      // Construct using com.trans.pixel.protoc.ExtraProto.Fenjie.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLootlistFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (lootlistBuilder_ == null) {
          lootlist_ = com.trans.pixel.protoc.Base.RewardInfo.getDefaultInstance();
        } else {
          lootlistBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_Fenjie_descriptor;
      }

      public com.trans.pixel.protoc.ExtraProto.Fenjie getDefaultInstanceForType() {
        return com.trans.pixel.protoc.ExtraProto.Fenjie.getDefaultInstance();
      }

      public com.trans.pixel.protoc.ExtraProto.Fenjie build() {
        com.trans.pixel.protoc.ExtraProto.Fenjie result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.trans.pixel.protoc.ExtraProto.Fenjie buildPartial() {
        com.trans.pixel.protoc.ExtraProto.Fenjie result = new com.trans.pixel.protoc.ExtraProto.Fenjie(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (lootlistBuilder_ == null) {
          result.lootlist_ = lootlist_;
        } else {
          result.lootlist_ = lootlistBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trans.pixel.protoc.ExtraProto.Fenjie) {
          return mergeFrom((com.trans.pixel.protoc.ExtraProto.Fenjie)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trans.pixel.protoc.ExtraProto.Fenjie other) {
        if (other == com.trans.pixel.protoc.ExtraProto.Fenjie.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLootlist()) {
          mergeLootlist(other.getLootlist());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.trans.pixel.protoc.ExtraProto.Fenjie parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.trans.pixel.protoc.ExtraProto.Fenjie) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;
      private com.trans.pixel.protoc.Base.RewardInfo lootlist_ = com.trans.pixel.protoc.Base.RewardInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.trans.pixel.protoc.Base.RewardInfo, com.trans.pixel.protoc.Base.RewardInfo.Builder, com.trans.pixel.protoc.Base.RewardInfoOrBuilder> lootlistBuilder_;
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      public boolean hasLootlist() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      public com.trans.pixel.protoc.Base.RewardInfo getLootlist() {
        if (lootlistBuilder_ == null) {
          return lootlist_;
        } else {
          return lootlistBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      public Builder setLootlist(com.trans.pixel.protoc.Base.RewardInfo value) {
        if (lootlistBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lootlist_ = value;
          onChanged();
        } else {
          lootlistBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      public Builder setLootlist(
          com.trans.pixel.protoc.Base.RewardInfo.Builder builderForValue) {
        if (lootlistBuilder_ == null) {
          lootlist_ = builderForValue.build();
          onChanged();
        } else {
          lootlistBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      public Builder mergeLootlist(com.trans.pixel.protoc.Base.RewardInfo value) {
        if (lootlistBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              lootlist_ != com.trans.pixel.protoc.Base.RewardInfo.getDefaultInstance()) {
            lootlist_ =
              com.trans.pixel.protoc.Base.RewardInfo.newBuilder(lootlist_).mergeFrom(value).buildPartial();
          } else {
            lootlist_ = value;
          }
          onChanged();
        } else {
          lootlistBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      public Builder clearLootlist() {
        if (lootlistBuilder_ == null) {
          lootlist_ = com.trans.pixel.protoc.Base.RewardInfo.getDefaultInstance();
          onChanged();
        } else {
          lootlistBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      public com.trans.pixel.protoc.Base.RewardInfo.Builder getLootlistBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLootlistFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      public com.trans.pixel.protoc.Base.RewardInfoOrBuilder getLootlistOrBuilder() {
        if (lootlistBuilder_ != null) {
          return lootlistBuilder_.getMessageOrBuilder();
        } else {
          return lootlist_;
        }
      }
      /**
       * <code>optional .com.trans.pixel.protoc.RewardInfo lootlist = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.trans.pixel.protoc.Base.RewardInfo, com.trans.pixel.protoc.Base.RewardInfo.Builder, com.trans.pixel.protoc.Base.RewardInfoOrBuilder> 
          getLootlistFieldBuilder() {
        if (lootlistBuilder_ == null) {
          lootlistBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.trans.pixel.protoc.Base.RewardInfo, com.trans.pixel.protoc.Base.RewardInfo.Builder, com.trans.pixel.protoc.Base.RewardInfoOrBuilder>(
                  lootlist_,
                  getParentForChildren(),
                  isClean());
          lootlist_ = null;
        }
        return lootlistBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.trans.pixel.protoc.Fenjie)
    }

    static {
      defaultInstance = new Fenjie(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.trans.pixel.protoc.Fenjie)
  }

  public interface FenjieListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.trans.pixel.protoc.Fenjie data = 1;
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    java.util.List<com.trans.pixel.protoc.ExtraProto.Fenjie> 
        getDataList();
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    com.trans.pixel.protoc.ExtraProto.Fenjie getData(int index);
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    java.util.List<? extends com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.trans.pixel.protoc.FenjieList}
   */
  public static final class FenjieList extends
      com.google.protobuf.GeneratedMessage
      implements FenjieListOrBuilder {
    // Use FenjieList.newBuilder() to construct.
    private FenjieList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FenjieList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FenjieList defaultInstance;
    public static FenjieList getDefaultInstance() {
      return defaultInstance;
    }

    public FenjieList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FenjieList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<com.trans.pixel.protoc.ExtraProto.Fenjie>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readMessage(com.trans.pixel.protoc.ExtraProto.Fenjie.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_FenjieList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_FenjieList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trans.pixel.protoc.ExtraProto.FenjieList.class, com.trans.pixel.protoc.ExtraProto.FenjieList.Builder.class);
    }

    public static com.google.protobuf.Parser<FenjieList> PARSER =
        new com.google.protobuf.AbstractParser<FenjieList>() {
      public FenjieList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FenjieList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FenjieList> getParserForType() {
      return PARSER;
    }

    // repeated .com.trans.pixel.protoc.Fenjie data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.trans.pixel.protoc.ExtraProto.Fenjie> data_;
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    public java.util.List<com.trans.pixel.protoc.ExtraProto.Fenjie> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    public java.util.List<? extends com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    public com.trans.pixel.protoc.ExtraProto.Fenjie getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
     */
    public com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.trans.pixel.protoc.ExtraProto.FenjieList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.trans.pixel.protoc.ExtraProto.FenjieList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.trans.pixel.protoc.FenjieList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.trans.pixel.protoc.ExtraProto.FenjieListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_FenjieList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_FenjieList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.trans.pixel.protoc.ExtraProto.FenjieList.class, com.trans.pixel.protoc.ExtraProto.FenjieList.Builder.class);
      }

      // Construct using com.trans.pixel.protoc.ExtraProto.FenjieList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.trans.pixel.protoc.ExtraProto.internal_static_com_trans_pixel_protoc_FenjieList_descriptor;
      }

      public com.trans.pixel.protoc.ExtraProto.FenjieList getDefaultInstanceForType() {
        return com.trans.pixel.protoc.ExtraProto.FenjieList.getDefaultInstance();
      }

      public com.trans.pixel.protoc.ExtraProto.FenjieList build() {
        com.trans.pixel.protoc.ExtraProto.FenjieList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.trans.pixel.protoc.ExtraProto.FenjieList buildPartial() {
        com.trans.pixel.protoc.ExtraProto.FenjieList result = new com.trans.pixel.protoc.ExtraProto.FenjieList(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.trans.pixel.protoc.ExtraProto.FenjieList) {
          return mergeFrom((com.trans.pixel.protoc.ExtraProto.FenjieList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.trans.pixel.protoc.ExtraProto.FenjieList other) {
        if (other == com.trans.pixel.protoc.ExtraProto.FenjieList.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.trans.pixel.protoc.ExtraProto.FenjieList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.trans.pixel.protoc.ExtraProto.FenjieList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.trans.pixel.protoc.Fenjie data = 1;
      private java.util.List<com.trans.pixel.protoc.ExtraProto.Fenjie> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<com.trans.pixel.protoc.ExtraProto.Fenjie>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.trans.pixel.protoc.ExtraProto.Fenjie, com.trans.pixel.protoc.ExtraProto.Fenjie.Builder, com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder> dataBuilder_;

      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public java.util.List<com.trans.pixel.protoc.ExtraProto.Fenjie> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.Fenjie getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder setData(
          int index, com.trans.pixel.protoc.ExtraProto.Fenjie value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder setData(
          int index, com.trans.pixel.protoc.ExtraProto.Fenjie.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder addData(com.trans.pixel.protoc.ExtraProto.Fenjie value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder addData(
          int index, com.trans.pixel.protoc.ExtraProto.Fenjie value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder addData(
          com.trans.pixel.protoc.ExtraProto.Fenjie.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder addData(
          int index, com.trans.pixel.protoc.ExtraProto.Fenjie.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.trans.pixel.protoc.ExtraProto.Fenjie> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.Fenjie.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public java.util.List<? extends com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.Fenjie.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.trans.pixel.protoc.ExtraProto.Fenjie.getDefaultInstance());
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public com.trans.pixel.protoc.ExtraProto.Fenjie.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.trans.pixel.protoc.ExtraProto.Fenjie.getDefaultInstance());
      }
      /**
       * <code>repeated .com.trans.pixel.protoc.Fenjie data = 1;</code>
       */
      public java.util.List<com.trans.pixel.protoc.ExtraProto.Fenjie.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.trans.pixel.protoc.ExtraProto.Fenjie, com.trans.pixel.protoc.ExtraProto.Fenjie.Builder, com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.trans.pixel.protoc.ExtraProto.Fenjie, com.trans.pixel.protoc.ExtraProto.Fenjie.Builder, com.trans.pixel.protoc.ExtraProto.FenjieOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.trans.pixel.protoc.FenjieList)
    }

    static {
      defaultInstance = new FenjieList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.trans.pixel.protoc.FenjieList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trans_pixel_protoc_Star_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_trans_pixel_protoc_Star_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trans_pixel_protoc_StarList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_trans_pixel_protoc_StarList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trans_pixel_protoc_Fenjie_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_trans_pixel_protoc_Fenjie_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_trans_pixel_protoc_FenjieList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_trans_pixel_protoc_FenjieList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ExtraProto.proto\022\026com.trans.pixel.prot" +
      "oc\032\nBase.proto\"b\n\004Star\022\n\n\002id\030\001 \001(\005\022\020\n\010ma" +
      "xlevel\030\002 \001(\005\022\020\n\010maxskill\030\003 \001(\005\022\014\n\004star\030\004" +
      " \001(\005\022\r\n\005level\030\005 \001(\005\022\r\n\005count\030\006 \001(\005\"6\n\010St" +
      "arList\022*\n\004data\030\001 \003(\0132\034.com.trans.pixel.p" +
      "rotoc.Star\"J\n\006Fenjie\022\n\n\002id\030\001 \001(\005\0224\n\010loot" +
      "list\030\002 \001(\0132\".com.trans.pixel.protoc.Rewa" +
      "rdInfo\":\n\nFenjieList\022,\n\004data\030\001 \003(\0132\036.com" +
      ".trans.pixel.protoc.Fenjie"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_trans_pixel_protoc_Star_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_trans_pixel_protoc_Star_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_trans_pixel_protoc_Star_descriptor,
              new java.lang.String[] { "Id", "Maxlevel", "Maxskill", "Star", "Level", "Count", });
          internal_static_com_trans_pixel_protoc_StarList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_trans_pixel_protoc_StarList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_trans_pixel_protoc_StarList_descriptor,
              new java.lang.String[] { "Data", });
          internal_static_com_trans_pixel_protoc_Fenjie_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_trans_pixel_protoc_Fenjie_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_trans_pixel_protoc_Fenjie_descriptor,
              new java.lang.String[] { "Id", "Lootlist", });
          internal_static_com_trans_pixel_protoc_FenjieList_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_trans_pixel_protoc_FenjieList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_trans_pixel_protoc_FenjieList_descriptor,
              new java.lang.String[] { "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.trans.pixel.protoc.Base.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
